#include "robomongo/bson/bson.h"

#include <chrono>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <iomanip>
#include <random>
#include <stdexcept>

namespace mongo {

    using detail::BSONValue;
    using detail::BSONValuePtr;

    // -----------------------------------------------------------------
    // OID / Date_t
    // -----------------------------------------------------------------

    OID OID::gen() {
        // 12 random bytes as hex; good enough for client-side temporary ids -
        // real ids are generated by mongosh/the server
        static thread_local std::mt19937_64 rng{std::random_device{}()};
        std::ostringstream ss;
        ss << std::hex << std::setfill('0');
        for (int i = 0; i < 3; ++i)
            ss << std::setw(8) << static_cast<uint32_t>(rng());
        return OID(ss.str().substr(0, 24));
    }

    std::ostream &operator<<(std::ostream &s, const OID &o) {
        return s << o.toString();
    }

    std::string Date_t::toString() const {
        std::time_t secs = static_cast<std::time_t>(_millis / 1000);
        std::tm tmv{};
#ifdef _WIN32
        gmtime_s(&tmv, &secs);
#else
        gmtime_r(&secs, &tmv);
#endif
        char buf[32];
        std::strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%S", &tmv);
        char out[48];
        std::snprintf(out, sizeof(out), "%s.%03dZ", buf, static_cast<int>(_millis % 1000));
        return out;
    }

    // -----------------------------------------------------------------
    // BSONElement
    // -----------------------------------------------------------------

    namespace {
        const std::string kEmptyString;
    }

    std::string BSONElement::String() const {
        if (!_value) return std::string();
        switch (_value->type) {
            case mongo::String:
            case Symbol:
            case Code:
                return _value->str;
            default:
                return std::string();
        }
    }

    const char *BSONElement::valuestr() const {
        return _value ? _value->str.c_str() : kEmptyString.c_str();
    }

    int BSONElement::valuestrsize() const {
        return _value ? static_cast<int>(_value->str.size()) + 1 : 1;
    }

    double BSONElement::numberDouble() const {
        if (!_value) return 0;
        switch (_value->type) {
            case NumberDouble: return _value->numberDouble;
            case NumberInt: return _value->numberInt;
            case NumberLong: return static_cast<double>(_value->numberLong);
            case mongo::Bool: return _value->boolean ? 1 : 0;
            default: return 0;
        }
    }

    int BSONElement::numberInt() const {
        if (!_value) return 0;
        switch (_value->type) {
            case NumberDouble: return static_cast<int>(_value->numberDouble);
            case NumberInt: return _value->numberInt;
            case NumberLong: return static_cast<int>(_value->numberLong);
            case mongo::Bool: return _value->boolean ? 1 : 0;
            default: return 0;
        }
    }

    long long BSONElement::numberLong() const {
        if (!_value) return 0;
        switch (_value->type) {
            case NumberDouble: return static_cast<long long>(_value->numberDouble);
            case NumberInt: return _value->numberInt;
            case NumberLong: return _value->numberLong;
            case mongo::Bool: return _value->boolean ? 1 : 0;
            default: return 0;
        }
    }

    Decimal128 BSONElement::numberDecimal() const {
        if (_value && _value->type == NumberDecimal) return Decimal128(_value->str);
        return Decimal128();
    }

    bool BSONElement::Bool() const {
        return _value ? _value->boolean : false;
    }

    bool BSONElement::trueValue() const {
        if (!_value) return false;
        switch (_value->type) {
            case mongo::Bool: return _value->boolean;
            case NumberDouble: return _value->numberDouble != 0;
            case NumberInt: return _value->numberInt != 0;
            case NumberLong: return _value->numberLong != 0;
            case jstNULL:
            case Undefined:
                return false;
            default: return true;
        }
    }

    OID BSONElement::OID() const {
        return _value ? _value->oid : mongo::OID();
    }

    Date_t BSONElement::date() const {
        return _value ? _value->date : Date_t();
    }

    Timestamp BSONElement::timestamp() const {
        return _value ? _value->timestamp : Timestamp();
    }

    Date_t BSONElement::timestampTime() const {
        return Date_t::fromMillisSinceEpoch(
            static_cast<long long>(timestamp().getSecs()) * 1000);
    }

    const char *BSONElement::regex() const {
        return _value ? _value->str.c_str() : kEmptyString.c_str();
    }

    const char *BSONElement::regexFlags() const {
        return _value ? _value->str2.c_str() : kEmptyString.c_str();
    }

    std::string BSONElement::_asCode() const {
        return _value ? _value->str : std::string();
    }

    BinDataType BSONElement::binDataType() const {
        return _value ? _value->binSubType : BinDataGeneral;
    }

    const char *BSONElement::binData(int &len) const {
        if (!_value) { len = 0; return kEmptyString.c_str(); }
        len = static_cast<int>(_value->binary.size());
        return _value->binary.data();
    }

    BSONObj BSONElement::embeddedObject() const {
        if (_value && (_value->type == Object || _value->type == mongo::Array))
            return BSONObj(_value);
        return BSONObj();
    }

    BSONObj BSONElement::Obj() const { return embeddedObject(); }

    BSONObj BSONElement::codeWScopeObject() const {
        if (_value && _value->scope) return BSONObj(_value->scope);
        return BSONObj();
    }

    std::vector<BSONElement> BSONElement::Array() const {
        std::vector<BSONElement> result;
        if (_value && (_value->type == mongo::Array || _value->type == Object))
            for (const auto &f : _value->fields)
                result.emplace_back(f.first, f.second);
        return result;
    }

    std::string BSONElement::dbrefNS() const {
        return _value ? _value->str : std::string();
    }

    std::string BSONElement::dbrefOID() const {
        return _value ? _value->str2 : std::string();
    }

    // -----------------------------------------------------------------
    // BSONObj
    // -----------------------------------------------------------------

    BSONObj::BSONObj() : _root(BSONValue::makeObject()) {}

    BSONObj::BSONObj(BSONValuePtr root)
        : _root(root ? std::move(root) : BSONValue::makeObject()) {}

    bool BSONObj::isEmpty() const {
        return _root->fields.empty();
    }

    int BSONObj::nFields() const {
        return static_cast<int>(_root->fields.size());
    }

    BSONElement BSONObj::getField(const std::string &name) const {
        for (const auto &f : _root->fields)
            if (f.first == name)
                return BSONElement(f.first, f.second);
        return BSONElement();
    }

    BSONElement BSONObj::firstElement() const {
        if (_root->fields.empty()) return BSONElement();
        return BSONElement(_root->fields[0].first, _root->fields[0].second);
    }

    std::string BSONObj::getStringField(const std::string &name) const {
        return getField(name).String();
    }

    int BSONObj::getIntField(const std::string &name) const {
        BSONElement e = getField(name);
        return e.eoo() ? -1 : e.numberInt();
    }

    bool BSONObj::getBoolField(const std::string &name) const {
        BSONElement e = getField(name);
        return !e.eoo() && e.trueValue();
    }

    BSONObj BSONObj::getObjectField(const std::string &name) const {
        return getField(name).embeddedObject();
    }

    bool BSONObj::isArray() const {
        return _root->type == mongo::Array;
    }

    void BSONObj::markAsArray() {
        _root->type = mongo::Array;
    }

    // -----------------------------------------------------------------
    // Iterators
    // -----------------------------------------------------------------

    bool BSONObjIterator::more() const {
        return _index < _root->fields.size();
    }

    BSONElement BSONObjIterator::next() {
        if (!more()) return BSONElement();
        const auto &f = _root->fields[_index++];
        return BSONElement(f.first, f.second);
    }

    BSONElement BSONObjStlIterator::operator*() const {
        const auto &f = _root->fields[_index];
        return BSONElement(f.first, f.second);
    }

    BSONObjStlIterator begin(const BSONObj &obj) {
        return BSONObjStlIterator(obj.root(), 0);
    }

    BSONObjStlIterator end(const BSONObj &obj) {
        return BSONObjStlIterator(obj.root(), obj.root()->fields.size());
    }

    // -----------------------------------------------------------------
    // Builders
    // -----------------------------------------------------------------

    namespace {
        BSONValuePtr makeScalar(BSONType t) {
            auto v = std::make_shared<BSONValue>();
            v->type = t;
            return v;
        }
    }

    BSONObjBuilder::BSONObjBuilder() : _root(BSONValue::makeObject()) {}

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, const std::string &value) {
        auto v = makeScalar(mongo::String);
        v->str = value;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, const char *value) {
        return append(name, std::string(value));
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, int value) {
        auto v = makeScalar(NumberInt);
        v->numberInt = value;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, long long value) {
        auto v = makeScalar(NumberLong);
        v->numberLong = value;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, double value) {
        auto v = makeScalar(NumberDouble);
        v->numberDouble = value;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, bool value) {
        auto v = makeScalar(mongo::Bool);
        v->boolean = value;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, const BSONObj &value) {
        _root->fields.emplace_back(name, value.root());
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, const mongo::OID &value) {
        auto v = makeScalar(jstOID);
        v->oid = value;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, const Date_t &value) {
        auto v = makeScalar(mongo::Date);
        v->date = value;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, const Timestamp &value) {
        auto v = makeScalar(bsonTimestamp);
        v->timestamp = value;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const std::string &name, const Decimal128 &value) {
        auto v = makeScalar(NumberDecimal);
        v->str = value.toString();
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::append(const BSONElement &elem) {
        if (!elem.eoo())
            _root->fields.emplace_back(elem.fieldNameStr(), elem.valuePtr());
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendArray(const std::string &name, const BSONObj &array) {
        auto root = array.root();
        root->type = mongo::Array;
        _root->fields.emplace_back(name, root);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendElements(const BSONObj &obj) {
        for (const auto &f : obj.root()->fields)
            _root->fields.emplace_back(f);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendNull(const std::string &name) {
        _root->fields.emplace_back(name, makeScalar(jstNULL));
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendUndefined(const std::string &name) {
        _root->fields.emplace_back(name, makeScalar(Undefined));
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendMinKey(const std::string &name) {
        _root->fields.emplace_back(name, makeScalar(MinKey));
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendMaxKey(const std::string &name) {
        _root->fields.emplace_back(name, makeScalar(MaxKey));
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendRegex(const std::string &name, const std::string &pattern,
                                                const std::string &options) {
        auto v = makeScalar(RegEx);
        v->str = pattern;
        v->str2 = options;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendBinData(const std::string &name, int len,
                                                  BinDataType type, const char *data) {
        auto v = makeScalar(BinData);
        v->binary.assign(data, static_cast<size_t>(len));
        v->binSubType = type;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendCode(const std::string &name, const std::string &code) {
        auto v = makeScalar(Code);
        v->str = code;
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendCodeWScope(const std::string &name,
                                                     const std::string &code,
                                                     const BSONObj &scope) {
        auto v = makeScalar(CodeWScope);
        v->str = code;
        v->scope = scope.root();
        _root->fields.emplace_back(name, v);
        return *this;
    }

    BSONObjBuilder &BSONObjBuilder::appendTimestamp(const std::string &name, unsigned secs,
                                                    unsigned inc) {
        return append(name, Timestamp(secs, inc));
    }

    BSONObj BSONObjBuilder::obj() {
        return BSONObj(_root);
    }

    BSONArrayBuilder::BSONArrayBuilder() : _root(BSONValue::makeArray()) {}

    namespace {
        std::string nextIndexName(const BSONValuePtr &root) {
            return std::to_string(root->fields.size());
        }
    }

    BSONArrayBuilder &BSONArrayBuilder::append(const std::string &value) {
        auto v = makeScalar(mongo::String);
        v->str = value;
        _root->fields.emplace_back(nextIndexName(_root), v);
        return *this;
    }

    BSONArrayBuilder &BSONArrayBuilder::append(const char *value) {
        return append(std::string(value));
    }

    BSONArrayBuilder &BSONArrayBuilder::append(int value) {
        auto v = makeScalar(NumberInt);
        v->numberInt = value;
        _root->fields.emplace_back(nextIndexName(_root), v);
        return *this;
    }

    BSONArrayBuilder &BSONArrayBuilder::append(long long value) {
        auto v = makeScalar(NumberLong);
        v->numberLong = value;
        _root->fields.emplace_back(nextIndexName(_root), v);
        return *this;
    }

    BSONArrayBuilder &BSONArrayBuilder::append(double value) {
        auto v = makeScalar(NumberDouble);
        v->numberDouble = value;
        _root->fields.emplace_back(nextIndexName(_root), v);
        return *this;
    }

    BSONArrayBuilder &BSONArrayBuilder::append(bool value) {
        auto v = makeScalar(mongo::Bool);
        v->boolean = value;
        _root->fields.emplace_back(nextIndexName(_root), v);
        return *this;
    }

    BSONArrayBuilder &BSONArrayBuilder::append(const BSONObj &value) {
        _root->fields.emplace_back(nextIndexName(_root), value.root());
        return *this;
    }

    BSONArrayBuilder &BSONArrayBuilder::append(const BSONElement &elem) {
        if (!elem.eoo())
            _root->fields.emplace_back(nextIndexName(_root), elem.valuePtr());
        return *this;
    }

    BSONArray BSONArrayBuilder::arr() {
        BSONObj obj(_root);
        return BSONArray(obj);
    }

    // -----------------------------------------------------------------
    // Utilities
    // -----------------------------------------------------------------

    namespace str {
        std::string escape(const std::string &in, bool escape_slash) {
            std::string out;
            out.reserve(in.size() + 8);
            for (char c : in) {
                switch (c) {
                    case '"': out += "\\\""; break;
                    case '\\': out += "\\\\"; break;
                    case '\b': out += "\\b"; break;
                    case '\f': out += "\\f"; break;
                    case '\n': out += "\\n"; break;
                    case '\r': out += "\\r"; break;
                    case '\t': out += "\\t"; break;
                    case '/':
                        if (escape_slash) { out += "\\/"; break; }
                        [[fallthrough]];
                    default:
                        if (static_cast<unsigned char>(c) < 0x20) {
                            char buf[8];
                            std::snprintf(buf, sizeof(buf), "\\u%04x", c);
                            out += buf;
                        } else {
                            out += c;
                        }
                }
            }
            return out;
        }
    }

    namespace base64 {
        namespace {
            const char kAlphabet[] =
                "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        }

        std::string encode(const char *data, int len) {
            std::string out;
            out.reserve(((len + 2) / 3) * 4);
            for (int i = 0; i < len; i += 3) {
                unsigned triple = (static_cast<unsigned char>(data[i]) << 16);
                if (i + 1 < len) triple |= (static_cast<unsigned char>(data[i + 1]) << 8);
                if (i + 2 < len) triple |= static_cast<unsigned char>(data[i + 2]);
                out += kAlphabet[(triple >> 18) & 0x3F];
                out += kAlphabet[(triple >> 12) & 0x3F];
                out += (i + 1 < len) ? kAlphabet[(triple >> 6) & 0x3F] : '=';
                out += (i + 2 < len) ? kAlphabet[triple & 0x3F] : '=';
            }
            return out;
        }

        void encode(std::stringstream &ss, const char *data, int len) {
            ss << encode(data, len);
        }

        std::string decode(const std::string &encoded) {
            auto val = [](char c) -> int {
                if (c >= 'A' && c <= 'Z') return c - 'A';
                if (c >= 'a' && c <= 'z') return c - 'a' + 26;
                if (c >= '0' && c <= '9') return c - '0' + 52;
                if (c == '+') return 62;
                if (c == '/') return 63;
                return -1;
            };
            std::string out;
            int buffer = 0, bits = 0;
            for (char c : encoded) {
                int v = val(c);
                if (v < 0) continue;  // skip padding/whitespace
                buffer = (buffer << 6) | v;
                bits += 6;
                if (bits >= 8) {
                    bits -= 8;
                    out += static_cast<char>((buffer >> bits) & 0xFF);
                }
            }
            return out;
        }
    }

    std::string toHexLower(const void *in, int len) {
        static const char hexchars[] = "0123456789abcdef";
        const unsigned char *data = static_cast<const unsigned char *>(in);
        std::string out;
        out.reserve(len * 2);
        for (int i = 0; i < len; ++i) {
            out += hexchars[data[i] >> 4];
            out += hexchars[data[i] & 0xF];
        }
        return out;
    }

    HexParseResult fromHex(const char *twoHexChars) {
        auto nibble = [](char c) -> int {
            if (c >= '0' && c <= '9') return c - '0';
            if (c >= 'a' && c <= 'f') return c - 'a' + 10;
            if (c >= 'A' && c <= 'F') return c - 'A' + 10;
            return 0;
        };
        return HexParseResult{
            static_cast<char>((nibble(twoHexChars[0]) << 4) | nibble(twoHexChars[1]))};
    }

    namespace logger {
        std::string LogSeverity::toString() const {
            switch (_severity) {
                case 0: return "SEVERE";
                case 1: return "ERROR";
                case 2: return "WARNING";
                case 3: return "INFO";
                case 4: return "LOG";
                default: return "DEBUG";
            }
        }
    }

    std::string HostAndPort::toString() const {
        return _host + ":" + std::to_string(_port);
    }
}
